"""update  Message class

Revision ID: 3174423f0fdc
Revises: 05fb941870e6
Create Date: 2024-08-07 11:48:00.447996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3174423f0fdc'
down_revision = '05fb941870e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
