"""add Message table

Revision ID: 5e00a8f76a56
Revises: 3174423f0fdc
Create Date: 2024-08-07 22:39:33.548008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e00a8f76a56'
down_revision = '3174423f0fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
