"""add Message class

Revision ID: ecd6000d1736
Revises: 8a74ffe1b8d4
Create Date: 2024-08-07 11:31:01.422331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd6000d1736'
down_revision = '8a74ffe1b8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###
